bucket_name: "noaa-enterprise-rainrate-pds"
root_prefix: "BLEND/RainRate-Blend-INST"
search_hours_back: 4
request_timeout_seconds: 30
headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
output_directory: "input/nc/"
max_files_to_keep: 12